from hal9.targets.docker import deploy as deploy_docker
from hal9.targets.hal9 import deploy as deploy_hal9
import datetime
import os

targets = {
  'docker': deploy_docker,
  'hal9': deploy_hal9,
}

def deploy(path :str = ".", target :str = "hal9", url :str = "https://api.hal9.com", name :str = None, typename :str = "ability", data :str = None, access :str = "private", main :str = "app.py", title :str = None, description :str = None) -> str:
  """Deploy an application to the Hal9 server.

  Requires a HAL9_TOKEN environment variable from https://hal9.com/devs.

  Parameters
  ----------
  path : str 
          Path to the application. Defaults to the current directory.
  target : str 
          The deployment target, defaults to 'hal9'.
  url : str
          The server url to deploy to. Defaults to https://api.hal9.com.
  name : str 
          The deployment name, automatically generated by default.
  typename : str
          The deployment type, defaults to (chatbot) ability.
  data : str
          The data schema to use, defaults to empty.
  access : str
          The access level, defaults to 'private'.
  main : str
          The main file to use, defaults to 'app.py'.
  title : str
          The deployment title, defaults to name.
  description : str
          The deployment description, defaults to empty.

  Returns
  -------
  str
          The URL of the deployed application.
  """

  if name is None:
    name = f'{os.path.basename(os.path.abspath(path))}-{int(datetime.datetime.now().timestamp() * 1000)}'

  if target in targets:
    return targets[target](path, url, name, typename, data, access, main, title, description)
  else:
    raise Exception(f"Deployment target '{target}' is unsupported.")
