#!/bin/sh

# You can use this pre-commit hook by directing Git to look
# for hooks in this directory using the following command
# at the repository root: git config core.hooksPath .githooks

# Prevent commits with BLOCK_GIT_COMMIT as an addtion in the staged diff
BLOCK_GIT_COMMIT_STRING='BLOCK_GIT_COMMIT'
if git diff --staged | grep -q "^+.*$BLOCK_GIT_COMMIT_STRING"
then
  echo "Git commit blocker string detected: $BLOCK_GIT_COMMIT_STRING"
  exit 1
fi
