[application]
name = "demo app"
version = "0.0.1"

# [client]
# design = "client.html"

[[runtimes]]
name = "r"
platform = "R"
# TODO: should support relative path from proj root
script = "./examples/my_app/R/backend.R"