# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_hal9_wrappers", use_symbols = TRUE, package_name = "hal9")

#' @docType package
#' @usage NULL
#' @useDynLib hal9, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Start server.
#' @export
h9_start2 <- function() .Call(wrap__h9_start2)

