# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_hal9_wrappers", use_symbols = TRUE, package_name = "hal9")

#' @docType package
#' @usage NULL
#' @useDynLib hal9, .registration = TRUE
NULL

#' Start server.
#' @export
h9_start <- function(path = ., port = NULL, timeout = 600, nobrowse = FALSE) invisible(.Call(wrap__h9_start, path, port, timeout, nobrowse))

#' Create a new demo app.
#' @export
h9_new <- function(path) invisible(.Call(wrap__h9_new, path))

