---
title: "Examples"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(python.reticulate = FALSE)
```

## Charts

```{r eval=FALSE, include=FALSE}
# explain more about charts here
```

### Bar

::: {.panel-tabset}

## R

```{r}
library(hal9)

h9_create() |>
  h9_load(mtcars) |>
  h9_bar_chart(x = "cyl",
               y = "carb",
               type = "grouped",
               orientation = "horizontal",
               palette = "schemePaired",
               fontsize = "14",
               tickrotation = "0",
               marginleft = "40",
               marginbottom = "30")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

```{r eval=FALSE, include=FALSE}

### Dot Plot



### Candles



### Heatmap

```

### Histogram

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_histogram_chart(x = "mpg",
                     histfunc = "count",
                     histnorm = "none",
                     barmode = "stack",
                     palette = "schemePaired")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

```{r eval=FALSE, include=FALSE}

### Line



### Sankey



### Scatter



### Treemap

```

### Line
  
::: {.panel-tabset}

## R

```{r}
tab_aux <- mtcars |> 
  dplyr::group_by(carb) |> 
  dplyr::summarise(media = mean(mpg))

h9_create() |>
  h9_load(tab_aux) |> 
  h9_line_chart(
    x = "carb",
    y = "media",
    palette = "schemePaired",
    fontsize = "16",
    marginleft = "40",
    marginbottom = "30"
  )
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Sankey

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |> 
  h9_sankey_chart(
    source = "carb",
    target = "cyl",
    value = "carb",
    palette = "schemePaired",
    fontsize = "16",
    marginleft = "40",
    marginbottom = "30"
  )
```

## Python

```{python, eval = FALSE}
"soon"
```

:::    

### Scatter
  
::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |> 
  h9_scatter_chart(
    x = "mpg",
    y = "drat",
    color = "cyl",
    size = "carb",
    palette = "schemePaired",
    fontsize = "16",
    marginleft = "40",
    marginbottom = "30"
  )
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Regression

::: {.panel-tabset}

## R

```{r}
tab_aux <- mtcars |> 
  dplyr::group_by(carb) |> 
  dplyr::summarise(media = mean(mpg))

h9_create() |>
  h9_load(tab_aux) |> 
  h9_regression_chart(
    x = "carb",
    y = "media",
    type = "exponential", 
    predictions = "0"
  )
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

## Transforms

### Assign

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_assign(column = "new_column", 
            array = "data.indices()")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

```{r eval=FALSE, include=FALSE}

### Convert

```

### Derive

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_derive(column = "new_column",
            expression = "data[columns[1]]")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Drop

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_drop(columns = "mpg")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Filter

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_filter(field = "mpg",
            expression = "field > 20")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Fold

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_fold(gather = "_row")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Impute

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(airquality) |>
  h9_impute(field = "Ozone",
            method = "mean")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

```{r eval=FALSE, include=FALSE}

### Pivot

```

### Rolling Sum

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_roll_sum(column = "mpg")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Sample

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_sample(samplesize = "40",
            withReplacement = "false")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Select

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_select(columns = "am")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Slice

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_slice(start = "5",
           end = "20")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Sort

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_sort(field = "mpg",
          order = "desc")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::

### Summarize

::: {.panel-tabset}

## R

```{r}
h9_create() |>
  h9_load(mtcars) |>
  h9_summarize(group = "cyl",
               field = "carb",
               summarizer = "mean")
```

## Python

```{python, eval = FALSE}
"soon"
```

:::


```{r eval=FALSE, include=FALSE}
## R Markdown

## Publish

## Shiny

```


