---
title: "Introduction"
format: html
editor: visual
---

Hal9's Enterprise plan enable your business users to answer data questions and find insights in seconds inside their own infrastructure with Hal9's conversational AI. 


This plan is recommended if:

* you work at a company with 200+ people
* you want to run everything on your own infrastructure, private cloud, AWS, Azure or Google account 
* you can not give access to third-party providers like Hal9


With this plan, your technical team can use [Docker](https://www.docker.com/) or [Kubernetes](https://kubernetes.io/) to install Hal9 within your data center or private virtual cloud. Hal9 will then transform and visualize all data entirely in your infrastructure and only process metadata in Hal9's LLM API. 


Hal9's LLM API lives in [hal9.com](https://hal9.com/) and it is the only component that will be outside the enterprise. As we mentioned before, we never take a look at your data and we only use the metadata (table names, table description and the input prompt). This is usually more than enough for many of the organizations but if you happen to be in a case where the application you use cannot even access to the internet, talk to us, we have a workaround to also run the model that we are using within your organization but it is quite complex and in most cases it is not necessary at all.
