name: Apps

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/apps*
      - apps/**

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install Hal9
        run: pip install hal9

  deploy_echo:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Deploy Echo
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/hal9/'; then
            hal9 deploy apps/echo --name ECHO --access public --title Echo --description "Echoes user input";
          else
            echo "No changes in apps/hal9. Skipping deployment.";
          fi
        env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}

  deploy_hal9:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Deploy Hal9
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/hal9/'; then
            hal9 deploy apps/hal9 --name hal9 --access public --title Hal9 --description "Conversations and content creation";
          else
            echo "No changes in apps/hal9. Skipping deployment.";
          fi
        env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}

  deploy_flux:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Deploy Flux
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/hal9/'; then
            hal9 deploy apps/flux --name flux --access public --title Flux --description "Photorealistic content creation";
          else
            echo "No changes in apps/hal9. Skipping deployment.";
          fi
        env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}

  deploy_browser:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Deploy Browser
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/hal9/'; then
            hal9 deploy apps/browser --name browser --access unlisted --title Browser --description "Capable of browsing the web";
          else
            echo "No changes in apps/hal9. Skipping deployment.";
          fi
        env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}

  deploy_openai:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Deploy OpenAI
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/hal9/'; then
            hal9 deploy apps/openai --name openai --access public --title OpenAI --description "Makes use of OpenAI O1";
          else
            echo "No changes in apps/hal9. Skipping deployment.";
          fi
        env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}
  
  deploy_swarm:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Deploy Swarm
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^apps/hal9/'; then
            hal9 deploy apps/swarm --name swarm --access public --title Swarm --description "Uses OpenAI's Swarm.";
          else
            echo "No changes in apps/hal9. Skipping deployment.";
          fi
        env:
          HAL9_TOKEN: ${{ secrets.HAL9_TOKEN }}
